[package]
name = "cas-repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.cas-eval]
path = "../cas-eval"

[dependencies.cas-parser]
path = "../cas-parser"
