[package]
name = "cas-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.18.2", features = ["png"] }
cas-compute = { path = "../cas-compute" }
cas-parser = { path = "../cas-parser" }
rayon = "1.7.0"
